.TH LVM 8 "LVM TOOLS" "Sistina Software UK" \" -*- nroff -*-
.SH NAME
lvm \- LVM2 tools
.SH SYNOPSIS
.B lvm
[command | file]
.SH DESCRIPTION
\fBlvm\fP provides the command-line tools for LVM2.  A separate
manual page describes each command in detail.
.LP
If \fBlvm\fP is invoked with no arguments it presents a readline prompt
(assuming it was compiled with readline support).
LVM commands may be entered interactively at this prompt with 
readline facilities including history and command name and option 
completion.  Refer to \fBreadline\fP(3) for details.
.LP
If \fBlvm\fP is invoked with argv[0] set to the name of a specific
LVM command (for example by using a hard or soft link) it acts as 
that command.  
.LP
One advantage of using the built-in shell is that configuration 
information is cached internally between commands.  
.LP
A file containing a simple script with one command per line 
can also be given on the command line.  The script can also be
executed directly if the first line is #! followed by the absolute
path of \fBlvm\fP.
.SH OPTIONS
The following options can be used with every command and are not documented
on individual manual pages.
.TP
\fB-h | --help\fP \(em Display the help text.
.TP
\fB--version\fP \(em Display the version.
Not implemented yet.
.TP
\fB-v | --verbose\fP \(em Set verbose level.
Repeat from 1 to 3 times to determine the detail of messages 
sent to stdout and stderr.  Overrides config file setting.
.TP
\fB-d | --debug\fP \(em Set debug level.
Repeat from 1 to 6 times to determine the detail of messages sent 
to the log file and/or syslog (if configured).
Overrides config file setting.
.TP
\fB--quiet\fP \(em Suppress output and log messages.
Overrides -d and -v.
.SH ENVIRONMENT VARIABLES
.TP
\fBLVM_SYSTEM_DIR\fP 
Directory containing lvm.conf and other LVM
system files.
Defaults to "/etc/lvm".
.TP
\fBHOME\fP 
Directory containing .lvm_history if the internal shell
is invoked.
.TP
\fBLVM_AUTOBACKUP\fP 
Set to "no" to disable automatic metadata
backups and archiving.  Not recommended.
Defaults to "yes".
.TP
\fBLVM_VG_NAME\fP 
The volume group name that is assumed for 
any reference to a logical volume that doesn't specify a path.
Not set by default.
.SH DIAGNOSTICS
All tools return a status code of zero on success or non-zero on failure.
.SH FILES
.I /etc/lvm/lvm.conf
.br
.I $HOME/.lvm_history
.SH SEE ALSO
.BR lvchange (8),
.BR lvcreate (8),
.BR lvdisplay (8),
.BR lvextend (8),
.BR lvmchange (8),
.BR lvreduce (8),
.BR lvremove (8),
.BR lvrename (8),
.BR lvresize (8),
.BR lvscan (8),
.BR pvchange (8),
.BR pvcreate (8),
.BR pvdisplay (8),
.BR pvscan (8),
.BR vgcfgbackup (8),
.BR vgchange  (8),
.BR vgck (8),
.BR vgcreate (8),
.BR vgdisplay (8),
.BR vgextend (8),
.BR vgmerge (8),
.BR vgreduce (8),
.BR vgremove (8),
.BR vgrename (8),
.BR vgscan (8),
.BR readline (3),
.BR lvm.conf (5)

