.TH LVREMOVE 8 "LVM TOOLS" "Sistina Software UK" \" -*- nroff -*-
.SH NAME
lvremove \- remove a logical volume
.SH SYNOPSIS
.B lvremove
[\-A/\-\-autobackup y/n] [\-d/\-\-debug] [\-f/\-\-force]
[\-h/\-?/\-\-help] 
[\-t/\-\-test]
[\-v/\-\-verbose] LogicalVolumePath [LogicalVolumePath...]
.SH DESCRIPTION
lvremove allows you to remove one or more inactive logical volumes.
.SH OPTIONS
See \fBlvm\fP for common options.
.TP
.I \-f, \-\-force
Force remove without confirmation.
.SH Example
"lvremove -f /dev/vg00/lvol1" removes that inactive logical volume
unconditionally.
.SH SEE ALSO
.BR lvm (8), 
.BR lvcreate (8), 
.BR lvdisplay (8), 
.BR lvscan (8)
