.TH PVDISPLAY 8 "LVM TOOLS" "Heinz Mauelshagen" \" -*- nroff -*-
.SH NAME
pvdisplay \- display attributes of a physical volume
.SH SYNOPSIS
.B pvdisplay
[\-c/\-\-colon] [\-d/\-\-debug] [\-h/\-?/\-\-help] [\-s/\-\-short]
[\-v[v]/\-\-verbose [\-\-verbose]]
PhysicalVolumePath [PhysicalVolumePath...]
.SH DESCRIPTION
pvdisplay allows you to see the attributes of one or more physical volumes
like size, physical extent size, space used for the volume group descriptor
area and so on.
.SS OPTIONS
.TP
.I \-c, \-\-colon
Generate colon seperated output for easier parsing in scripts or programs.
.nf

The values are:

* physical volume device name
* volume group name
* physical volume size in kilobytes
* internal physical volume number
* physical volume status
* physical volume (not) allocatable
* current number of logical volumes on this physical volume
* physical extent size in kilobytes
* total number of physical extents
* free number of physical extents
* allocated number of physical extents

.fi
.TP
.I \-d, \-\-debug
Enables additional debugging output (if compiled with DEBUG).
.TP
.I \-h, \-?, \-\-help
Print a usage message on standard output and exit successfully.
.TP
.I \-s, \-\-short
Only display the size of the given physical volumes.
.TP
.I \-v, \-\-verbose
Display the mapping of physical extents to logical volumes and
logical extents.
.TP
.I \-vv, \-\-verbose \-\-verbose
Like \-v with verbose runtime information about pvdisplay's activities.
.SH DIAGNOSTICS
pvdisplay returns an code state of 0 for success and > 0 for error:
.nf

1  no physical volume name on command line
2  error checking consistency of physical volume
3  error reading physical extent information from physical volume

95 driver/module not in kernel
96 invalid I/O protocol version
97 error locking logical volume manager
98 invalid lvmtab (run vgscan(8))
99 invalid command line
.fi
.SH See also
lvm(8), pvcreate(8), lvcreate(8), vgcreate(8)
.SH AUTHOR
Heinz Mauelshagen <Linux-LVM@Sistina.com>
