.TH VGCFGBACKUP 8 "LVM TOOLS" "Sistina Software UK" \" -*- nroff -*-
.SH NAME
vgcfgbackup \- backup volume group descriptor area
.SH SYNOPSIS
.B vgcfgbackup
.RB [ \-d | \-\-debug ]
.RB [ \-f | \-\-file " filename" ]
.RB [ \-h | \-\-help ]
.RB [ \-\-ignorelockingfailure ]
.RB [ \-P | \-\-partial ]
.RB [ \-v | \-\-verbose ]
.RI [ VolumeGroupName ...]
.SH DESCRIPTION
.B vgcfgbackup
allows you to backup the metadata 
of your volume groups.
If you don't name any volume groups on the command line, all of them 
will be backed up.  This DOESN'T backup user/system data in logical
volume(s)!  Backup /etc/lvm regularly too.
.SH OPTIONS
See \fBlvm\fP for common options.
.SH SEE ALSO
.BR lvm (8),
.BR vgcreate (8)
