.TH VGSCAN 8 "LVM TOOLS" "Sistina Software UK" \" -*- nroff -*-
.SH NAME
vgscan \- scan all disks for volume groups and rebuild caches
.SH SYNOPSIS
.B vgscan
[\-d/\-\-debug] [\-h/\-?/\-\-help] 
[\-\-ignorelockingfailure]
[\-P/\-\-partial]
[\-v/\-\-verbose]
.SH DESCRIPTION
vgscan scans all SCSI, (E)IDE disks, multiple devices and a bunch
of other disk devices in the system looking for LVM physical volumes
and volume groups.  Define a filter in \fBlvm.conf\fP(8) to restrict 
the scan to avoid a CD ROM, for example.
.LP
In LVM2, vgscans take place automatically; but you might still need to
run one explicitly after changing hardware or filters.
.SH OPTIONS
See \fBlvm\fP for common options.
.SH SEE ALSO
.BR lvm (8), 
.BR vgcreate (8), 
.BR vgchange (8)
