.TH VGSPLIT 8 "LVM TOOLS" "Sistina Software UK" \" -*- nroff -*-
.SH NAME
vgsplit \- split a volume group into two
.SH SYNOPSIS
.B vgsplit
.RB [ \-\-alloc
.IR AllocationPolicy ]
.RB [ \-A | \-\-autobackup " {" y | n }]
.RB [ \-c | \-\-clustered " {" y | n }]
.RB [ \-d | \-\-debug ]
.RB [ \-h | \-\-help ]
.RB [ \-l | \-\-maxlogicalvolumes
.IR MaxLogicalVolumes ]
.RB [ -M | \-\-metadatatype
.IR type ]
.RB [ -p | \-\-maxphysicalvolumes
.IR MaxPhysicalVolumes ]
.RB [ \-s | \-\-physicalextentsize
.IR PhysicalExtentSize [ \fBkKmMgGtT\fR ]]
.RB [ \-t | \-\-test ]
.RB [ \-v | \-\-verbose ]
SourceVolumeGroupName DestinationVolumeGroupName
PhysicalVolumePath [PhysicalVolumePath...]
.SH DESCRIPTION
.B vgsplit 
moves
.IR PhysicalVolumePath (s)
from
.I SourceVolumeGroupName
into
.I DestinationVolumeGroupName\fP.

If
.I DestinationVolumeGroupName
does not exist, a new volume group will be created.  The default attributes
for the new volume group can be specified with \fB\-\-alloc\fR,
\fB\-\-clustered\fR, \fB\-\-maxlogicalvolumes\fR, \fB\-\-metadatatype\fR,
\fB\-\-maxphysicalvolumes\fR, and \fB\-\-physicalextentsize\fR
(see \fBvgcreate(8)\fR for a description of these options).
If any of these options are not given, the default attribute(s) are taken
from
.I SourceVolumeGroupName\fP.

If
.I DestinationVolumeGroupName
does exist, it will be checked for compatibility with
.I SourceVolumeGroupName
before the physical volumes are moved.

Logical Volumes cannot be split between Volume Groups.
Each existing Logical Volume must be entirely on the Physical Volumes forming
either the source or the destination Volume Group.
.SH OPTIONS
See \fBlvm\fP for common options.
.SH SEE ALSO
.BR lvm (8), 
.BR vgcreate (8), 
.BR vgextend (8), 
.BR vgreduce (8),
.BR vgmerge (8)
