.TH VGSPLIT 8 "LVM TOOLS" "Sistina Software UK" \" -*- nroff -*-
.SH NAME
vgsplit \- split a volume group into two
.SH SYNOPSIS
.B vgsplit
[\-A/\-\-autobackup y/n] 
[\-d/\-\-debug] 
[\-h/\-?/\-\-help] 
[\-l/\-\-list]
[\-M/\-\-metadatatype 1/2]
[\-t/\-\-test] 
[\-v/\-\-verbose] 
SourceVolumeGroupName DestinationVolumeGroupName
PhysicalVolumePath [PhysicalVolumePath...]
.SH DESCRIPTION
.B vgsplit 
moves
.IR PhysicalVolumePath (s)
from
.I SourceVolumeGroupName
into
.I DestinationVolumeGroupName\fP.
If
.I DestinationVolumeGroupName
does not exist, it will be created.
Logical Volumes cannot be split between Volume Groups.
Each existing Logical Volume must be entirely on the Physical Volumes forming
either the source or the destination Volume Group.
.SH OPTIONS
See \fBlvm\fP for common options.
.SH SEE ALSO
.BR lvm (8), 
.BR vgcreate (8), 
.BR vgextend (8), 
.BR vgreduce (8),
.BR vgmerge (8)
