#!/bin/bash
#
# chkconfig: 345 24 76
# description: Starts and stops clvmd
#
#	       
### BEGIN INIT INFO
# Provides: 
### END INIT INFO

. /etc/init.d/functions

LVDISPLAY="/usr/sbin/lvdisplay"
VGCHANGE="/usr/sbin/vgchange"
VGSCAN="/usr/sbin/vgscan"

[ -f /etc/sysconfig/cluster ] && . /etc/sysconfig/cluster

LOCK_FILE="/var/lock/subsys/clvmd"

start()
{
	for rtrn in 0
	do
		if ! pidof clvmd > /dev/null 
		then 
			echo -n "Starting clvmd: "
			daemon clvmd
			rtrn=$?
			echo
			if [ $rtrn -ne 0 ]
			then
				break
			fi
 		fi	
		# refresh cache
		$VGSCAN  > /dev/null 2>&1
		
		if [ -n "$LVM_VGS" ]
		then
			for vg in $LVM_VGS
			do
				if action "Activating lvm $vg:" $VGCHANGE -ayl $vg
				then
					echo;
				else
					rtrn=$?
					echo;
                                fi
			done
		else
			if action "Activating lvms:" $VGCHANGE -ayl
			then
				echo;
			else
				rtrn=$?
				echo;
                        fi
		fi
	done

	return $rtrn
}

stop()
{
	for rtrn in 0
	do
		if [ -n "$LVM_VGS" ]
		then
			for vg in $LVM_VGS
			do
				if action "Deactivating lvm $vg:" $VGCHANGE -anl $vg
				then
					echo;
				else
					rtrn=$?
					echo;
				fi
			done
		else
			if action "Deactivating lvms:" if $VGCHANGE -anl
			then
				echo;
			else
				rtrn=$?
				echo;
			fi
		fi

		[ $rtrn -ne 0 ] && break

		echo -n "Stopping clvm:"
		killproc clvmd -TERM
		rtrn=$?
		echo
	done
	
	return $rtrn
}

rtrn=1

# See how we were called.
case "$1" in
  start)
	start
	rtrn=$?
	[ $rtrn = 0 ] && touch $LOCK_FILE
	;;

  stop)
	stop
	rtrn=$?
	[ $rtrn = 0 ] && rm -f $LOCK_FILE
	;;

  restart)
	if stop
	then
		start
	fi 
	rtrn=$?
	;;

  status)
	status clvmd
	vols=$( $LVDISPLAY -C --nohead 2> /dev/null | awk '($3 ~ /....a./) {print $1}' )
	echo active volumes: ${vols:-"(none)"}
	rtrn=0
	;;

  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	;;
esac

exit $rtrn
