#!/bin/bash
#
# Copyright (C) 2007 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing to use,
# modify, copy, or redistribute it subject to the terms and conditions
# of the GNU General Public License v.2.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This file is part of LVM2.
# It is required for the proper handling of failures of LVM2 mirror
# devices that were created using the -m option of lvcreate.
#
#
# chkconfig: 12345 02 99
# description: Starts and stops dmeventd monitoring for lvm2
#	       
### BEGIN INIT INFO
# Provides: 
### END INIT INFO

. /etc/init.d/functions

VGCHANGE="/usr/sbin/vgchange"

start()
{
    for ret in 0
    do
	# TODO do we want to separate out already active groups only?
	VGS=`vgs --noheadings -o name`
	for vg in $VGS
	do
	    if ! action "Starting monitoring for VG $vg:" $VGCHANGE --monitor y $vg
	    then
		ret=$?
	    fi
	done

    done

    return $ret
}


stop()
{
    for ret in 0
    do
	# TODO do we want to separate out already active groups only?
	VGS=`vgs --noheadings -o name`
	for vg in $VGS
	do
	    if ! action "Starting monitoring for VG $vg:" $VGCHANGE --monitor n $vg
	    then
		ret=$?
	    fi
	done

    done

}

ret=1

# See how we were called.
case "$1" in
  start)
	start
	ret=$?
	;;

  stop)
	stop
	ret=$?
	;;

  restart)
	if stop
	then
		start
	fi 
	ret=$?
	;;

  status)
	# TODO anyone with an idea how to dump monitored volumes?
	;;

  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	;;
esac

exit $ret
